Parameters:
  App:
    Type: String
    Description: Your application's name.
  Env:
    Type: String
    Description: The name of the environment being deployed.

Resources:
  markdowntable2:
    Metadata:
      'aws:copilot:description': 'An Amazon DynamoDB table for markdown-table2'
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${App}-${Env}-markdown-table2
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: ID
          KeyType: HASH

Outputs:
  markdowntable2Name:
    Description: "The name of this DynamoDB table."
    Value: !Ref markdowntable2
    Export: 
      Name: !Sub ${App}-${Env}-markdowntable2TableName
  markdowntable2DynamoDBTableARN:
    Description: "The ARN of the markdown-table2 DynamoDB table."
    Value: !GetAtt markdowntable2.Arn
    Export: 
      Name: !Sub ${App}-${Env}-markdowntable2TableArn
